load grep_rewrite.maude .

*** List of commands to be executed with the GREP tool, and the results 
*** that should appear on the screen.

rew is "ho" in "h" . "o" .
  *** true
rew is "hohoho" in ( "h" . "o" ) * .
  *** true
rew is "hello" in "hello" .
  *** true
rew is "ho" in ( "h" . "o" ) * .
  *** true
rew is "hola" in "h" . "o" . "l" . "a" .
  *** true
rew is "holahola" in "h" . "o" . "l" . "a" .
  *** false
rew is "holahola" in ("h" . "o" . "l" . "a") * .
  *** true
rew is "" in ( "h" . "o" . "l" . "a" ) * .
  *** true
rew is "hooo" in "h" . "o" * s "i" .
  *** true
rew is "i" in "h" . "o" * s "i" .
  *** true
rew is "hoho" in "h" . "o" * s "i" .
  *** false
